name: Master workflow

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          DB_CONNECTION: pgsql
          POSTGRES_DB: hex_project
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Setup project
        run: make setup

      - name: Check lint
        run: make lint

      - name: Run test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          POSTGRES_DB: hex_project
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        with:
          coverageCommand: make test-coverage
          coverageLocation: ${{github.workspace}}/coverage-report:clover
          debug: true
